repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=*]
      - id: check-json
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: double-quote-string-fixer
      - id: end-of-file-fixer

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--strict, -c=./.yamllint.yaml]
        exclude: ^.*templates.*$

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.19.0
    hooks:
      - id: terraform-docs-go
        args:
          [
            'markdown',
            'table',
            '--recursive',
            '--lockfile=false',
            '--output-file',
            'README.md',
            '--output-mode',
            'inject',
            '--hide',
            'requirements',
            '--hide',
            'providers',
            '--hide',
            'modules',
            './',
          ]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_tflint
      #- id: infracost_breakdown
      - id: terraform_checkov
        args:
          - --args=--config-file __GIT_WORKING_DIR__/.checkov.yaml
  # - id: tfupdate
  #   args:
  #     - --args=terraform
  #     - --args=-v ">=1.6.2"
  # - id: tfupdate
  #   args:
  #     - --args=provider helm
  # - id: tfupdate
  #   args:
  #     - --args=provider kubernetes
  # - id: tfupdate
  #   args:
  #     - --args=provider alekc/kubectl
  # - id: terraform_providers_lock
  #   name: provider locking for linux_amd64
  #   args:
  #     - '--args=-platform=linux_amd64'
  # - id: terraform_providers_lock
  #   name: provider locking for darwin_arm64
  #   args:
  #     - '--args=-platform=darwin_arm64'

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 38.94.3
    hooks:
      - id: renovate-config-validator
