branches:
  - main
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
  - - '@semantic-release/changelog'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
      message: "docs(changelog): ${nextRelease.version} \n\n${nextRelease.notes}"
  - '@semantic-release/github'
