---
extends: default

rules:
  line-length: disable
  indentation: disable
  document-start: disable
  brackets:
    max-spaces-inside: 1
  braces:
    max-spaces-inside: 1
  comments:
    require-starting-space: false
    min-spaces-from-content: 1
  truthy:
    check-keys: false
  colons:
    max-spaces-after: 10
