name: Check

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

on:
  pull_request:
    branches: ['main']

permissions: read-all

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip3 install checkov
      - run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - uses: pre-commit/action@v3.0.1
